# Generated by Django 5.0.1 on 2024-03-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicles_name', models.CharField(max_length=50)),
                ('vehicles_description', models.TextField()),
                ('vehicles_seat', models.IntegerField()),
                ('vehicles_door', models.IntegerField()),
                ('vehicles_luggage', models.IntegerField()),
                ('vehicles_price', models.IntegerField()),
                ('vehicles_image', models.FileField(default=None, max_length=250, null=True, upload_to='vehicles_image/')),
            ],
        ),
    ]
