# Generated by Django 5.0.1 on 2024-03-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicles_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
