# Generated by Django 5.0.1 on 2024-03-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicles_vehicles_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
